language: shell

jobs:
  include:
    - name: Debian 10 buster (amd64)
      os: linux
      env:
        - DEBIAN_RELEASE: buster
        - DEBIAN_ARCH: amd64
      services:
        - docker

    - name: Debian 10 buster (i386)
      os: linux
      env:
        - DEBIAN_RELEASE: buster
        - DEBIAN_ARCH: i386
      services:
        - docker

    - name: Debian 10 buster (arm64)
      os: linux
      env:
        - DEBIAN_RELEASE: buster
        - DEBIAN_ARCH: arm64
      services:
        - docker

    - name: Debian 10 buster (armhf)
      os: linux
      env:
        - DEBIAN_RELEASE: buster
        - DEBIAN_ARCH: armhf
      services:
        - docker

    - name: Debian 10 buster (mips64el)
      os: linux
      env:
        - DEBIAN_RELEASE: buster
        - DEBIAN_ARCH: mips64el
      services:
        - docker
        

before_install:
  - |-
      if [ -f docker_images/${DEBIAN_RELEASE}-${DEBIAN_ARCH}.tar.gz ]; then
        gzip -dc docker_images/${DEBIAN_RELEASE}-${DEBIAN_ARCH}.tar.gz | docker load
      else
        docker build -t docker-deb-builder:${DEBIAN_RELEASE}-${DEBIAN_ARCH} -f docker-deb-builder/Dockerfile-debian-${DEBIAN_RELEASE}-${DEBIAN_ARCH} .
      fi

before_cache:
  - |-
      if [ ! -f docker_images/${DEBIAN_RELEASE}-${DEBIAN_ARCH}.tar.gz ]; then
        docker save docker-deb-builder:${DEBIAN_RELEASE}-${DEBIAN_ARCH} | gzip > docker_images/${DEBIAN_RELEASE}-${DEBIAN_ARCH}.tar.gz
      fi

cache:
  directories:
    - docker_images
  
install:
  - ./scan-and-build.sh

script:
  - ./summary.sh
