
name: electron
license: MIT

only_arches:
  - amd64
  - i386
  - arm64
  - armhf

source:
  host: other
  get_version: curl -s 'https://archlinux.org/packages/community/x86_64/electron/json/' | python3 -c \"import sys, json; print(json.load(sys.stdin)['pkgver'])\"
  method: build
  source_url: empty

