
name: freechat
license: MIT

only_arches:
  - amd64
  - i386
  - arm64
  - armhf

source:
  host: other
  get_version: echo 1.0.0-patch2
  method: build
  source_url: https://github.com/eNkru/freechat/archive/3a8304e38098d3159daad4b9a735c903fe9353a8.zip
