
name: textadept
license: MIT

source:
  host: other
  get_version: curl -s 'https://orbitalquark.github.io/textadept/' | grep '<h2>Download' | sed 's/.*v\([0-9\.]*\).*/\1/g'
  method: build
  source_url: https://github.com/orbitalquark/textadept/archive/textadept_##VERSION.tar.gz
