
name: motrix
license: MIT

only_arches:
  - amd64
  - i386
  - arm64
  - armhf

source:
  host: other
  get_version: echo 1.6.11-patch1
  method: build
  source_url: https://github.com/CarterLi/Motrix/archive/c956cea9665642e5c3b476003fe308d13a66bc50.zip
