
name: draw.io
license: Apache-2.0

only_arches:
  - amd64
  - i386
  - arm64
  - armhf

source:
  host: github
  repo: jgraph/drawio-desktop
  method: build
  source_url: https://github.com/jgraph/drawio-desktop/releases/download/v##VERSION/drawio-amd64-##VERSION.deb
