
name: Build

on:
  push:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      - DEBIAN_RELEASE: bullseye
      - DEBIAN_ARCH: amd64
      - CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        run: docker build -t docker-deb-builder:${DEBIAN_RELEASE}-${DEBIAN_ARCH} -f docker-deb-builder/Dockerfile-debian-${DEBIAN_RELEASE}-${DEBIAN_ARCH} .

      - name: Install Cloudsmith Cli
        run: pip3 install cloudsmith-cli

      - name: Build and upload packages
        run: ./scan-and-build.sh

      - name: Remove outdated packages
        run: ./remove-outdated.sh

      - name: Summary
        run: ./summary.sh
